kratos.gid/apps/EmbeddedFluid/python/KratosFluid.py
kratos.gid/apps/Fluid/python/KratosFluid.py
kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/xml/SolutionStrategy.spd

Automatic time stepping now available in the interface

Automatic time stepping

---

kratos.gid/apps/EmbeddedFluid/xml/Strategies.xml
kratos.gid/apps/Fluid/xml/Strategies.xml

Clean up of the strategy parameters according to fluid dynamics python solvers updates.

Update fluid solvers strategy parameters

---

kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/xml/SolutionStrategy.spd

Adition of minimum delta time field when automatic time stepping is used.

Minimum delta time

---

kratos.gid/apps/Dam/python/dam_acoustic_script.py
kratos.gid/apps/Dam/python/dam_main.py
kratos.gid/apps/EmbeddedFluid/python/KratosFluid.py
kratos.gid/apps/FSI/python/KratosFSI.py
kratos.gid/apps/Fluid/python/KratosFluid.py
kratos.gid/apps/Structural/python/KratosSolid.py

Instead of a standard dictionary, now the Kratos Model() is used.

Using Kratos Model

---

kratos.gid/apps/FSI/python/KratosFSI.py
kratos.gid/apps/FSI/write/writeProjectParameters.tcl
kratos.gid/apps/FSI/xml/Coupling_solvers.xml
kratos.gid/apps/FSI/xml/Strategies.xml

Several updates and bug corrections according to the last developments. MainKratos.py file updated. Creation of a problem_data dict to store the parallelism info in the coupling solver settings. solve_mesh_at_each_iteration option added to the interface (deprecated mesh options do not appear anymore).

FSI application updates

---

kratos.gid/kratos.tcl
kratos.gid/scripts/Writing.tcl

This is just a patch, not a correction.

Fix invalid names

---

kratos.gid/apps/FSI/examples/HorizontalFlexibleBar.tcl
kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl
kratos.gid/apps/FSI/examples/examples.tcl

Fix fsi example

---

kratos.gid/apps/StenosisWizard/start.tcl
kratos.gid/apps/StenosisWizard/wizard/Wizard_Steps.tcl
kratos.gid/scripts/Wizard.tcl
kratos.gid/scripts/Writing.tcl

Fixed the Condition assigned
The writing bug will be fixed when #52 gets fixed

Fix stenosis wizard conditions

---

kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl

Fix fsi mok example repaired

---

kratos.gid/apps/Dam/xml/Processes.xml
kratos.gid/apps/Numa/xml/Processes.xml

#70 cleaning CheckDimension process

CheckDimension is not working for table

---

kratos.gid/apps/Dam/examples/ThermoMechaDam.tcl
kratos.gid/apps/Dam/examples/examples.tcl
kratos.gid/apps/Dam/start.tcl
kratos.gid/apps/Dam/xml/Processes.xml

Example finished

---

kratos.gid/apps/Dam/write/writeProjectParameters.tcl
kratos.gid/apps/Dam/xml/Processes.xml
kratos.gid/scripts/Writing.tcl
kratos.gid/scripts/spdAuxiliar.tcl

Fixes the issues of the deprecated state: CheckDimension on tables

#70 #72 Table parameters can be three dimensional (X Y Z)

---

kratos.gid/apps/FSI/python/KratosFSI.py

Addition of the auxiliar processes list to the constructed processes in the list_of_processes.

Auxiliar fluid processes construction added

---

kratos.gid/scripts/Model/Condition.tcl
kratos.gid/scripts/Writing.tcl

This fixes #86 
The problem only affected conditions with no topology features

Fixed nodal conditions bug at writing conditions #86

---

kratos.gid/apps/Common/xml/Processes.xml
kratos.gid/apps/Structural/start.tcl
kratos.gid/apps/Structural/xml/Conditions.xml
kratos.gid/apps/Structural/xml/GetFromXML.tcl

Structural Self weight was using a wrong process
It is still wrong since it is not using Density but thats not a gui issue
Also allows structural to use intervals

Structural Self weight was using a wrong process

---

kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl
kratos.gid/apps/FSI/xml/GetFromXML.tcl

- Disable MPI parallelism
- Bug correction and defatults update in Mok benchark case

Minor corrections

---

kratos.gid/apps/Structural/xml/NodalConditions.xml
kratos.gid/apps/Structural/xml/Processes.xml

Now using AssignVectorVariableProcess process #118 #104

Rotation, angular velocity and angular acceleration processes

---

kratos.gid/apps/Fluid/write/writeProjectParameters.tcl

The deprecated processes are not used anymore.

Update gravity process in FluidDynamicsApplication

---

kratos.gid/apps/Dam/python/dam_main.py
kratos.gid/apps/Dam/xml/Processes.xml
kratos.gid/apps/Dam/xml/Solution.spd

- Adding weeks in time scale option
- Definition of month variable as double for intermediate steps

Adding new time option

---

kratos.gid/kratos.unix.bat

fixing  the name of the python std library

---

kratos.gid/apps/Numa/xml/Conditions.xml
kratos.gid/apps/Numa/xml/Results.spd

There is an space after POSTIVE_FACE_PRESSURE

Name Error in NUMA Application

---

kratos.gid/apps/Dam/python/dam_main.py
kratos.gid/apps/Dam/write/write.tcl
kratos.gid/apps/Dam/write/writeProjectParameters.tcl
kratos.gid/apps/Dam/xml/Conditions.xml
kratos.gid/apps/Dam/xml/Loads.spd
kratos.gid/apps/Dam/xml/Main.spd
kratos.gid/apps/Dam/xml/Processes.xml
kratos.gid/apps/Dam/xml/ThermalLoads.spd

- Adding Uniform heat fluxes
- Adding T sol Air heat fluxes
- Uncommenting Added Mass condition
- Updating writting files according the new .spd

Adding thermal loads conditions

---

kratos.gid/apps/Dam/examples/ThermoMechaDam.tcl
kratos.gid/apps/Dam/python/dam_main_selfweight.py
kratos.gid/apps/Dam/write/write.tcl
kratos.gid/apps/Dam/write/writeProjectParameters.tcl
kratos.gid/apps/Dam/xml/Processes.xml
kratos.gid/apps/Dam/xml/Solution.spd

New script and new tabs for considering self weight as external problem. This is done just for summing the stresses to the normal problem but not displacements.

Consider the selfweight as external problem

---

kratos.gid/apps/Fluid/xml/Parts.spd
kratos.gid/apps/Solid/xml/Elements.xml
kratos.gid/apps/Structural/write/write.tcl
kratos.gid/apps/Structural/xml/Elements.xml
kratos.gid/apps/Structural/xml/GetFromXML.tcl
kratos.gid/apps/Structural/xml/Parts.spd
kratos.gid/kratos.tcl
kratos.gid/kratos_default.spd
kratos.gid/scripts/Applications.tcl
kratos.gid/scripts/Menus.tcl
kratos.gid/scripts/spdAuxiliar.tcl

This implements #103 
Please @RiccardoRossi try to create a line, assign a Small displacements beam, mesh and write. See the mdpa file

Add localaxes to beams

---

kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl
kratos.gid/apps/Structural/write/writeProjectParameters.tcl
kratos.gid/apps/Structural/xml/StageInfo.spd
kratos.gid/apps/Structural/xml/Strategies.xml

Dear all,
Finally we manage to keep all your changes except the "dynamic"/"static" field, which values are "Dynamic"/"Static" (the main reason is to keep the stable interface version until the released is packaged #159).
@loumalouomega is doing a PR in the StructuralMechanicsApplication to include such "Dynamic"/"Static"  modifications.
Hope this is ok for you.

Updating structural mechanics solvers#159

---

kratos.gid/apps/Common/xml/Processes.xml
kratos.gid/apps/Structural/xml/Conditions.xml
kratos.gid/apps/Structural/xml/Processes.xml

Some processes appeared twice in the StructuralApplication and in the common processes folder. Thus conflicts appeared.

Rearranging processes

---

kratos.gid/apps/EmbeddedFluid/write/write.tcl

The embedded fluid writing script was out of date.

Fix embedded fluid writing

---

kratos.gid/apps/Structural/xml/Elements.xml

Hotfix recover beams

---

kratos.gid/apps/Structural/examples/TrussCantilever.tcl
kratos.gid/apps/Structural/examples/examples.tcl
kratos.gid/apps/Structural/start.tcl
kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml
kratos.gid/apps/Structural/xml/Elements.xml
kratos.gid/scripts/spdAuxiliar.tcl

Please check the parameters (For the element, solvers and so)
Implements #161

Add truss example structural

---

kratos.gid/apps/Solid/xml/ConstitutiveLaws.xml

Missing  type="combo" in combo parameters #191

---

kratos.gid/apps/Common/xml/Conditions.xml
kratos.gid/apps/Common/xml/Elements.xml

Change some generic condition names  #158

---

kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml

delete Poisson ratio in Truss #200

---

kratos.gid/kratos.unix.bat

This will fix the "no platform libraries detected for xxx" error

Setting PYTHONHOME

---

.gitignore
kratos.gid/exec/Kratos/README.md

@jginternational Could we please maintain the exec dir with an empty README or something?
My exec is empty so not sure if the new rules for the ignore hold.

Adding empty exec/Kratos

---

kratos.gid/scripts/Writing.tcl

@rubenzorrilla This fixes that CustomVelocity parameters ghost 
Avanti with the cavity

Fixed vector parameters write. If elseif else structure was not stable

---

kratos.gid/kratos_default.spd

We temporary hide the Dam Application.

Removed Dam App

---

kratos.gid/apps/EmbeddedFluid/examples/CylinderInFlow.tcl
kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl
kratos.gid/apps/Fluid/examples/CylinderInFlow.tcl
kratos.gid/apps/Structural/examples/TrussCantilever.tcl

First iteration of the new groups policy.
Still missing "Draw groups" in CustomLib -> GiD side

Update groups policy in example

---

kratos.gid/apps/Structural/write/writeProjectParameters.tcl
kratos.gid/apps/Structural/xml/NodalConditions.xml
kratos.gid/apps/Structural/xml/SolutionStrategy.spd
kratos.gid/apps/Structural/xml/StageInfo.spd

Added Quasi-Static
It acts as Static, but shows and prints time parameters
Implements #219

Feature quasi static structural

---

kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/xml/Conditions.xml
kratos.gid/scripts/Model/Condition.tcl
kratos.gid/scripts/Writing.tcl

You can test it
Implements #240

Feature grouped submodelparts by condition #240

---

kratos.gid/scripts/spdAuxiliar.tcl

RenameIntervalGroup only store information about modified groups.

---

kratos.gid/apps/Solid/xml/GetFromXML.tcl
kratos.gid/scripts/Model/Element.tcl
kratos.gid/scripts/Model/SolutionStrategy.tcl

Check it @josep-m-carbonell 
If you can bring an example where the situation in #248 was happening I can check it too

Enhacement solution strategies with no elements hidden #248

---

kratos.gid/apps/EmbeddedFluid/examples/CylinderInFlow.tcl
kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl
kratos.gid/apps/Fluid/examples/CylinderInFlow.tcl

Fixing examples of FLUID and derivated Embedded and FSI

Hotfix fluid fix examples

---

kratos.gid/apps/FSI/xml/Strategies.xml
kratos.gid/scripts/Model/SolutionStrategy.tcl
kratos.gid/scripts/spdAuxiliar.tcl

An update for filtering elementless strategies and schemes broke this.

Hotfix fsi no strategies coupled

---

kratos.gid/kratos.tcl
kratos.gid/scripts/Menus.tcl

Feature write and run only #259

---

kratos.gid/scripts/Model/ConstitutiveLaw.tcl
kratos.gid/scripts/Writing.tcl

Feature constitutive law write name 2

---

kratos.gid/apps/Structural/postprocess/formfinding.tcl
kratos.gid/apps/Structural/start.tcl

Feature formfinding

---

kratos.gid/apps/DEM/write/write.tcl
kratos.gid/apps/DEM/write/writeMDPA_Inlet.tcl
kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl
kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
kratos.gid/scripts/Writing.tcl

Properties id consecutive for DEM files

---

kratos.gid/apps/Structural/python/KratosStructural.py

This PR brings the main script up to date with the latest developments

[StructuralMechanics] Updating MainScript

---

kratos.gid/apps/DEM/examples/examples.tcl
kratos.gid/apps/DEM/start.tcl
kratos.gid/apps/EmbeddedFluid/examples/examples.tcl
kratos.gid/apps/EmbeddedFluid/start.tcl
kratos.gid/apps/FSI/examples/examples.tcl
kratos.gid/apps/FSI/start.tcl
kratos.gid/apps/Fluid/examples/examples.tcl
kratos.gid/apps/Fluid/start.tcl
kratos.gid/apps/Structural/examples/examples.tcl
kratos.gid/apps/Structural/start.tcl
kratos.gid/kratos.tcl
kratos.gid/scripts/Applications.tcl
kratos.gid/scripts/Menus.tcl
kratos.gid/scripts/spdAuxiliar.tcl

New Feature
New appid::CustomMenus event is called after the app is fully loaded, so it can change the GiD Menu

Fix examples menu numeration

---

kratos.gid/scripts/spdAuxiliar.tcl

Material can change with no Element or Constitutive law

---

kratos.gid/apps/DEM/write/writeMDPA_Inlet.tcl
kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl
kratos.gid/apps/EmbeddedFluid/write/writeProjectParameters.tcl
kratos.gid/apps/FSI/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
kratos.gid/apps/Pfem/write/write.tcl
kratos.gid/apps/Pfem/write/writeProjectParameters.tcl
kratos.gid/apps/PfemFluid/write/write.tcl
kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl
kratos.gid/apps/Solid/write/write.tcl
kratos.gid/apps/Structural/write/write.tcl
kratos.gid/kratos.tcl
kratos.gid/scripts/Deprecated.tcl
kratos.gid/scripts/Writing.tcl

Enhacement change all mesh to submodelpat

---

kratos.gid/apps/MPM/xml/ConstitutiveLaws.xml
kratos.gid/apps/MPM/xml/GetFromXML.tcl
kratos.gid/apps/MPM/xml/Procs.spd

Hotfix mpm elements

---

kratos.gid/apps/DEM/examples/SpheresDrop.tcl

Fix dem example parameters

---

kratos.gid/apps/Structural/xml/Conditions.xml

Add Point Moment for 3D #227

---

kratos.gid/apps/EmbeddedFluid/python/KratosFluid.py
kratos.gid/apps/Fluid/python/KratosFluid.py

@rubenzorrilla I've tested the example embedded problem and it seems to work with the new fluid analysis, so I've gone ahead and replaced both main scripts. I did not push directly to master to give you a chance to do some more tests, but feel free to merge once you think it is ready.

Fluid/Embedded python scripts use the new analysis class.

---

kratos.gid/apps/Fluid/xml/Processes.xml
kratos.gid/scripts/spdAuxiliar.tcl

Hotfix repair parameters dependencies #316

---

kratos.gid/apps/Fluid/xml/Processes.xml
kratos.gid/apps/Structural/write/writeProjectParameters.tcl
kratos.gid/apps/Structural/xml/Elements.xml
kratos.gid/apps/Structural/xml/GetFromXML.tcl
kratos.gid/apps/Structural/xml/StageInfo.spd
kratos.gid/apps/Structural/xml/Strategies.xml
kratos.gid/scripts/Model/Element.tcl
kratos.gid/scripts/Writing.tcl
kratos.gid/scripts/spdAuxiliar.tcl

Feature add prestressed membrane

---

kratos.gid/apps/Structural/xml/NodalConditions.xml

Fixed the boundary conditions
Fixes #331

Fixed BC for formfindings #331

---

kratos.gid/apps/Fluid/python/KratosFluid.py

This updates the interface to match PR 1904 in Kratos.

Updating to match changes in Fluid application.

---

kratos.gid/apps/Structural/write/write.tcl
kratos.gid/apps/Structural/write/writeProjectParameters.tcl
kratos.gid/scripts/Model/Element.tcl
kratos.gid/scripts/Writing.tcl

@maceligueta check if it's working

Hotfix structural contact

---

kratos.gid/apps/Structural/python/KratosStructural.py

[Structural] Using the new AnalysisStage

---

kratos.gid/apps/Structural/xml/Elements.xml

see [PR in Kratos](https://github.com/KratosMultiphysics/Kratos/pull/2113)

[Structural] removing old membrane

---

kratos.gid/scripts/Writing.tcl

Optional parameters protection #360

---

kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/apps/StenosisWizard/wizard/Wizard_Steps.tcl

#332 Fixed interaction with Fluid app write module

---

kratos.gid/apps/Structural/xml/Conditions.xml
kratos.gid/apps/Structural/xml/Processes.xml

Pressure on lines does not work with functions yet

---

kratos.gid/apps/Structural/start.tcl

Assign old conditions only in lines assigned to groups

---

kratos.gid/apps/EmbeddedFluid/start.tcl

Set Embedded mesher

---

kratos.gid/apps/Structural/xml/GetFromXML.tcl

[Release 6.0]Do not write CONDENSED_DOF_LIST as post process variable

---

kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml

Besides, the 2D should not give as option plain stress? @KratosMultiphysics/structural-mechanics

Missing hyperelastic laws in strucural

---

kratos.gid/apps/FSI/python/KratosFSI.py

@jginternational this makes the FSI interface compatible with the changes in #2068. Of course this is a temporary solution until the FSI analysis stage is implemented.
Please, merge this once you have created the Release 6.0 branch.

Updating FSI main script to use Kratos Model in structure solver

---

kratos.gid/apps/FSI/python/KratosFSI.py

For after the release. This synchronizes the main script with the changes in https://github.com/KratosMultiphysics/Kratos/pull/2277

Updating FSI main script.

---

kratos.gid/scripts/spdAuxiliar.tcl

#399 More button not working

---

README.md
kratos.gid/kratos.tcl
kratos.gid/kratos.xml
kratos.gid/kratos_default.spd
kratos.gid/scripts/spdAuxiliar.tcl

Feature transform from older version

---

kratos.gid/apps/Structural/write/write.tcl
kratos.gid/scripts/Applications.tcl
kratos.gid/scripts/Writing.tcl

I think it's enough
Fixes #379

Feature add validation before write

---

kratos.gid/kratos.tcl
kratos.gid/kratos.xml
kratos.gid/kratos_default.spd
kratos.gid/scripts/Controllers/CommonProcs.tcl
kratos.gid/scripts/spdAuxiliar.tcl

Bugfix variables restored #409

---

kratos.gid/apps/Solid/start.tcl
kratos.gid/apps/Solid/write/validation.tcl
kratos.gid/scripts/Model/Condition.tcl
kratos.gid/scripts/Model/Element.tcl

Solid validation before write

---

kratos.gid/apps/DEM/xml/Materials.xml

Added materials, copied data from G-Dempack
Please check:
- PARTICLE_FRICTION >Coefficient of friction
I couldn't find it in the old database

Added new DEM materials

---

kratos.gid/apps/Solid/xml/NodalConditions.xml
kratos.gid/apps/Solid/xml/Processes.xml
kratos.gid/scripts/Controllers/CommonProcs.tcl
kratos.gid/scripts/Controllers/TreeInjections.tcl
kratos.gid/scripts/Writing.tcl

Adding compound assignment option for nodal conditions #430

adding compound assignment combo in nodal conditions

---

kratos.gid/apps/MPM/xml/ConstitutiveLaws.xml

Hi @jginternational, I am working currently on a new constitutive law in MPM. There is one thing that I would like to ask you before pushing this branch to the master. If you think that it is possible to implement, can you help me with that? Thanks in advance.

[MPM] Adding new cam clay CLs

---

kratos.gid/apps/DEM/write/writeProjectParameters.tcl
kratos.gid/apps/DEMPFEM/examples/InnerSphere.tcl
kratos.gid/apps/DEMPFEM/start.tcl
kratos.gid/kratos_default.spd

pfem dem - Dimension and remesh

---

kratos.gid/apps/EmbeddedFluid/write/write.tcl
kratos.gid/apps/FSI/write/write.tcl
kratos.gid/apps/FSI/write/writeProjectParameters.tcl
kratos.gid/apps/FSI/xml/GetFromXML.tcl
kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/apps/Fluid/write/writeByGiDId.tcl
kratos.gid/scripts/Model/SolutionStrategy.tcl
kratos.gid/scripts/Writing/Writing.tcl

@rubenzorrilla Check python scripts in Kratos side

Hotfix fsi write

---

kratos.gid/apps/Common/xml/Parallelism.spd
kratos.gid/apps/Common/xml/Results.spd
kratos.gid/apps/DEM/write/writeProjectParameters.tcl
kratos.gid/apps/DEM/xml/Gravity.spd
kratos.gid/apps/DEM/xml/Results.spd
kratos.gid/apps/DEM/xml/SolutionStrategy.spd
kratos.gid/apps/DEMPFEM/examples/InnerSphere.tcl
kratos.gid/apps/DEMPFEM/write/writeProjectParameters.tcl
kratos.gid/apps/DEMPFEM/xml/GetFromXML.tcl
kratos.gid/apps/DEMPFEM/xml/Main.spd
kratos.gid/apps/DEMPFEM/xml/TimeParameters.spd
kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl
kratos.gid/apps/PfemFluid/xml/GetFromXML.tcl
kratos.gid/apps/PfemFluid/xml/TimeSettings.spd
kratos.gid/scripts/Controllers/TreeInjections.tcl

@maceligueta 
- Parallel config
- Time parameters
- Gravity
- Intervals

Pfemdem common params

---

kratos.gid/apps/Buoyancy/write/writeProjectParameters.tcl
kratos.gid/apps/Buoyancy/xml/GetFromXML.tcl
kratos.gid/apps/ConvectionDiffusion/write/write.tcl
kratos.gid/apps/ConvectionDiffusion/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
kratos.gid/apps/Structural/write/write.tcl
kratos.gid/apps/Structural/write/writeProjectParameters.tcl
kratos.gid/scripts/Writing/WriteProjectParameters.tcl
kratos.gid/scripts/Writing/Writing.tcl

@rubenzorrilla 
Ya hace el output

Buoyancy upgrade write

---

kratos.gid/apps/Fluid/write/write.tcl

Fixes #476
Can you try it @jcotela  ?

Backwards compat with gid 13 in MergeGroups

---

kratos.gid/apps/FSI/write/write.tcl
kratos.gid/apps/FSI/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/examples/CylinderInFlow.tcl
kratos.gid/apps/Fluid/start.tcl
kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/xml/GetFromXML.tcl
kratos.gid/apps/Fluid/xml/Main.spd
kratos.gid/apps/Structural/start.tcl
kratos.gid/apps/Structural/write/write.tcl
kratos.gid/apps/Structural/write/writeProjectParameters.tcl
kratos.gid/apps/Structural/xml/GetFromXML.tcl
kratos.gid/apps/Structural/xml/Main.spd
kratos.gid/scripts/Writing/WriteProjectParameters.tcl

I think it's done.
I'm checking it on your branch on linux
@rubenzorrilla

Fsi new write json

---

kratos.gid/apps/EmbeddedFluid/write/writeProjectParameters.tcl
kratos.gid/apps/EmbeddedFluid/xml/Strategies.xml
kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/xml/Strategies.xml

I tried with both examples of the Fluid (body-fitted) and EmbeddedFluid apps. and writes and works. Maybe the implementation can be improved but I cannot see how. Have a look to it.

[Fluid] Formulation settings

---

kratos.gid/apps/MPM/write/write.tcl
kratos.gid/apps/MPM/write/writeProjectParameters.tcl
kratos.gid/apps/MPM/xml/Main.spd
kratos.gid/kratos.tcl

Fixes #491
@bodhinandach You'll need to generate the case again to test

Hotfix mpm

---

kratos.gid/apps/EmbeddedFluid/write/write.tcl

Fixes #492
@merceln @maceligueta

Add modelpart name Fluid embedded

---

kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
kratos.gid/apps/ConjugateHeatTransfer/examples/examples.tcl
kratos.gid/apps/ConjugateHeatTransfer/start.tcl
kratos.gid/apps/ConjugateHeatTransfer/write/writeProjectParameters.tcl
kratos.gid/apps/ConvectionDiffusion/write/writeProjectParameters.tcl

@rubenzorrilla Try it please, I can't run it. It's the second example in the toolbar

Add bfs cht

---

kratos.gid/scripts/Writing/WriteProjectParameters.tcl

using the new vtk-output-process
FYI @KratosMultiphysics/technical-committee @KratosMultiphysics/interface-committee 
so far it only supports nodal-solution-step-results

adding basic vtk-output

---

kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
kratos.gid/apps/ConjugateHeatTransfer/examples/HeatedSquare.tcl
kratos.gid/apps/ConjugateHeatTransfer/write/writeProjectParameters.tcl
kratos.gid/apps/ConjugateHeatTransfer/xml/Conditions.xml
kratos.gid/apps/ConjugateHeatTransfer/xml/GetFromXML.tcl
kratos.gid/apps/ConjugateHeatTransfer/xml/SolutionStrategy.spd

Some CHT application clean up and fixes.

[ConvDiff] CHT interface cleanup and BFS example fix

---

kratos.gid/apps/Common/xml/Solvers.xml
kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
kratos.gid/apps/ConjugateHeatTransfer/examples/HeatedSquare.tcl
kratos.gid/apps/ConvectionDiffusion/examples/HeatedSquare.tcl
kratos.gid/apps/MPM/xml/GetFromXML.tcl

This should fix the solver naming issue #512

Removed forced solver and solver name with parent

---

kratos.gid/apps/FSI/xml/SolutionStrategy.spd

To match the current kratos master
I am not sure which names are the correct ones to update though

updating mesh-solver names

---

kratos.gid/apps/Buoyancy/xml/Parts.spd
kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl

@jginternational FYI this solves the injection problem I told you.

[Buoyancy][CHT] CHT BFS updating set up

---

kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
kratos.gid/apps/ConjugateHeatTransfer/xml/Conditions.xml
kratos.gid/apps/ConvectionDiffusion/xml/Conditions.xml
kratos.gid/apps/ConvectionDiffusion/xml/Processes.xml

New condition to set the boundary thermal behavior (so far only adiabatic condition could be considered). The thermal interface condition is now based on the new thermal face process.
A minor bug in the BFS was spotted and corrected during the validation of the new condition. 
(wait for the Kratos process merge to merge this)

[ConvDiff][Buoyancy][CHT] Creation of new thermal face condition.

---

kratos.gid/apps/Structural/write/write.tcl
kratos.gid/scripts/Writing/Writing.tcl

add modelpart prefix in materials json

---

kratos.gid/apps/ConvectionDiffusion/examples/HeatedSquare.tcl

This avoids the example to set the Dirichlet BCs as initial conditions.

[ConvDiff] Example intervals fix

---

kratos.gid/apps/DEMPFEM/xml/Procs.spd

Add missing proc

---

kratos.gid/apps/Buoyancy/examples/HeatedSquare.tcl
kratos.gid/apps/Buoyancy/start.tcl

Enlarge total time, default mesh settings and more descriptive example name

[Buoyancy] Minor changes to reach steady state

---

kratos.gid/apps/ConjugateHeatTransfer/xml/Main.spd

Add materials to convection diffusion in CHT

---

kratos.gid/apps/Fluid/examples/CylinderInFlow.tcl

Minor fix in the inlet intervals.

[Fluid] Example intervals hotfix

---

kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl

Minor fix in BCs part of the script.

[CHT] BFS minor fixes

---

kratos.gid/apps/FSI/examples/TurekBenchmark.tcl

Change Turek benchmark example mesh & settings to ensure convergence.
@jginternational I think that after merging this we can say that the FSI GUI is ready to be released.
closes #549

[FSI] Turek benchmark settings

---

kratos.gid/apps/DEM/xml/Materials.xml

missing constitutive law field added and cohesion field now depends on the selected law

[DEM]added missing field in materials

---

kratos.gid/apps/Structural/xml/Elements.xml

making membrane avaiable in release mode

---

kratos.gid/apps/CDEM/write/writeProjectParameters.tcl
kratos.gid/apps/DEM/start.tcl
kratos.gid/apps/DEM/write/writeProjectParameters.tcl
kratos.gid/apps/DEMLauncher/start.tcl
kratos.gid/apps/FluidDEM/start.tcl

and removed CDEM since it is unfinished.

[SDEM]fix advanced meshing options in SDEM

---

kratos.gid/apps/Stent/wizard/StentGeometry.tcl
kratos.gid/apps/Stent/wizard/StentGeometry_default.wiz

@agiuliodori @soudah 
FIxes #565

Fix stent geometry

---

kratos.gid/apps/FluidDEM/python/MainKratos.py

@GuillermoCasas Replacing the PFEM one.

[SDEM]replacing MainKratos with the correct file

---

kratos.gid/apps/DEM/write/writeMDPA_Inlet.tcl
kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl
kratos.gid/apps/DEM/xml/Conditions.xml
kratos.gid/apps/DEM/xml/Processes.xml

update interface for inlet condition

[DEM]inlet interface

---

kratos.gid/apps/Stent/wizard/StentGeometry.tcl
kratos.gid/apps/Stent/wizard/StentGeometry_default.wiz

@jginternational   Can you check the new-version of the Stent-Crimped?

Updating Stent Interface

---

kratos.gid/scripts/Menus.tcl

Check if menu exists

---

kratos.gid/apps/Structural/examples/examples.tcl
kratos.gid/apps/Structural/start.tcl

@rubenzorrilla 
I understand that the HighRiseBuilding example is only for 2D.
I've hidden it for 3D.
Merge if you agree.
Add it for 3D if you think it should be also in 3D

Fix structural example 3d

---

kratos.gid/apps/DEM/examples/SpheresDrop.tcl
kratos.gid/apps/DEM/write/writeMDPA_Inlet.tcl
kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl
kratos.gid/apps/DEM/xml/Conditions.xml
kratos.gid/apps/DEM/xml/Processes.xml

DEM example and some write procs were old

---

kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/scripts/Writing/WriteConditionsByUniqueId.tcl
kratos.gid/scripts/Writing/WriteSubModelPart.tcl

Fix write custom submodelpart by unique id 

---

kratos.gid/apps/Fluid/xml/ConstitutiveLaws.xml
kratos.gid/apps/Fluid/xml/GetFromXML.tcl
kratos.gid/scripts/Model/ConstitutiveLaw.tcl

@rubenzorrilla @GuillermoCasas

Feature non newtonian fluid

---

kratos.gid/kratos.tcl
kratos.gid/scripts/Applications.tcl
kratos.gid/scripts/Controllers/ApplicationMarketWindow.tcl
kratos.gid/scripts/Controllers/TreeInjections.tcl
kratos.gid/scripts/Logs.tcl
kratos.gid/scripts/Writing/WriteProjectParameters.tcl

A log is stored in the temp location

Feature add logs

---

kratos.gid/apps/Buoyancy/xml/Parts.spd
kratos.gid/apps/CDEM/xml/Parts.spd
kratos.gid/apps/DEM/start.tcl
kratos.gid/apps/DEM/write/write_utils.tcl
kratos.gid/apps/DEM/xml/Parts.spd

@farrufat-cimne 
@KratosMultiphysics/dem
The important change is in the ovm field of the Part condition in parts.spd 
was:
`ovm="element"`
and needed:
`ovm="node,element"`
The rest is just stylings and apply default values to things

Fix after mesh generation special for DEM

---

kratos.gid/apps/Structural/write/write.tcl
kratos.gid/apps/Structural/write/writeProjectParameters.tcl
kratos.gid/scripts/Writing/WriteProjectParameters.tcl
kratos.gid/scripts/Writing/Writing.tcl

in order to use the default of the solver
=> see https://github.com/KratosMultiphysics/Kratos/pull/4978 (already merged)

remove lists of SMPs for ComputingModelPart

---

kratos.gid/apps/PotentialFluid/examples/NACA0012.tcl
kratos.gid/apps/PotentialFluid/xml/Elements.xml
kratos.gid/apps/PotentialFluid/xml/Processes.xml
kratos.gid/apps/PotentialFluid/xml/Strategies.xml

Small PR updating the interface for the potential flow application

Potential app update json

---

kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl

added elements list in submp.
@jgonzalezusua

hotfix for wall mdpa

---

kratos.gid/apps/Stent/wizard/StentGeometry.tcl

Now joint directions point to the center of the 'cylinder'

Hotfix stent normals

---

kratos.gid/apps/Structural/write/writeProjectParameters.tcl

Check it @loumalouomega @AlejandroCornejo

Remove contact limit

---

kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl
kratos.gid/scripts/Writing/WriteProjectParameters.tcl

@AFranci please, could you attach here an example of pfemfluid ProjectParameters so I can see the output configuration?

PFEM Fluid - Try result output

---

kratos.gid/apps/Fluid/write/writeProjectParameters.tcl

This hardcodes `reform_dofs_at_each_step` to `False` as we agreed in [here](https://github.com/KratosMultiphysics/Kratos/issues/5229). The change is automatically applied in the FSI GUI.

[Fluid][FSI] reform_dofs_at_each_step default False

---

kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/apps/PotentialFluid/start.tcl
kratos.gid/apps/PotentialFluid/xml/Conditions.xml
kratos.gid/apps/PotentialFluid/xml/Processes.xml

@inigolcanalejo merge when ready!

Potential flow 3d

---

kratos.gid/apps/Buoyancy/python/MainKratos.py
kratos.gid/apps/ConjugateHeatTransfer/python/KratosConjugateHeatTransfer.py
kratos.gid/apps/ConjugateHeatTransfer/python/MainKratos.py
kratos.gid/apps/DEM/python/KratosDEMAnalysis.py
kratos.gid/apps/EmbeddedFluid/python/KratosFluid.py
kratos.gid/apps/FluidDEM/python/MainKratos.py

I updated the remaining old-style imports to have less troubles when moving to the py-modules

Update py imports

---

kratos.gid/apps/DEM/xml/Processes.xml
kratos.gid/scripts/Controllers/TreeInjections.tcl

added hide in windows for the other processes
to be merged on new gid deploy

[Dem]parent selection bug

---

kratos.gid/apps/PotentialFluid/examples/NACA0012.tcl
kratos.gid/apps/PotentialFluid/xml/GetFromXML.tcl

Potential 3d example

---

kratos.gid/apps/PfemFluid/xml/ConstitutiveLaws.xml
kratos.gid/scripts/Writing/WriteMaterials.tcl
kratos.gid/scripts/Writing/Writing.tcl
kratos.gid/scripts/spdAuxiliar.tcl

This tries to fix the bug happened to some apps like Pfem Fluid. That printed wrong values if the tree was closed

Fix need to open the tree

---

kratos.gid/apps/DEM/write/writeMDPA_Inlet.tcl
kratos.gid/apps/DEM/xml/SolutionStrategy.spd

Cluster files are copied to the case folder. Other corrections are introduced.

Fixing clusters + cosmetics

---

kratos.gid/apps/CDEM/start.tcl
kratos.gid/apps/CDEM/write/writeMDPA_Walls.tcl
kratos.gid/apps/CDEM/write/writeProjectParameters.tcl
kratos.gid/apps/CDEM/xml/SolutionStrategy.spd
kratos.gid/apps/DEM/write/write_utils.tcl
kratos.gid/apps/DEM/xml/Processes.xml

writing in json and mdpa of material test options OK.
python functions regarding material testing not tested.

[DEM]integrated material testing options in tree

---

kratos.gid/apps/Structural/write/write.tcl
kratos.gid/kratos.tcl
kratos.gid/scripts/Controllers/Preferences.xml
kratos.gid/scripts/Controllers/PreferencesWindow.tcl
kratos.gid/scripts/Writing/WriteConditions.tcl
kratos.gid/scripts/Writing/WriteConditionsByGiDId.tcl
kratos.gid/scripts/Writing/WriteConditionsByUniqueId.tcl
kratos.gid/scripts/Writing/WriteNodes.tcl
kratos.gid/scripts/Writing/WriteSubModelPart.tcl
kratos.gid/scripts/Writing/Writing.tcl

Implements #665 
I think that the improvement is about the 40%
To switch between the Optimized and the readable modes:
1.  Open the preferences window 
- Ctrl + p
- Preferences icon
- Utilities > Preferences
- Kratos > Kratos preferences)
2. Kratos section
3. MDPA Optimization

Feature optimization mdpa

---

kratos.gid/apps/CDEM/write/writeMDPA_Parts.tcl
kratos.gid/apps/DEM/write/writeMDPA_Inlet.tcl
kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl

It was totally wrong, both for particles and inlets. Walls worked ok.

[dem] Important bugfix for Friction

---

kratos.gid/apps/DEM/xml/Parts.spd
kratos.gid/apps/DEM/xml/Procs.spd
kratos.gid/apps/DEM/xml/XmlController.tcl

[dem] Parts can select different types of entities depending on number of dimensions

---

kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
kratos.gid/apps/DEM/xml/Processes.xml
kratos.gid/apps/DEM/xml/XmlController.tcl
kratos.gid/scripts/Controllers/CommonProcs.tcl
kratos.gid/scripts/Controllers/MdpaImportMesh.tcl
kratos.gid/scripts/Controllers/TreeInjections.tcl
kratos.gid/scripts/Model/Parameter.tcl

@farrufat-cimne Maybe you need to change the printing process for inertia. You can do it in this branch.
@maceligueta fixes #691

Hotfix dem inertia

---

kratos.gid/apps/PfemFluid/write/write.tcl
kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl

Pfem fluid submodelpart names

---

kratos.gid/scripts/Controllers/CommonProcs.tcl

@farrufat-cimne test to fix #703

Conditions parameters - missing clausule

---

kratos.gid/apps/CDEM/write/writeProjectParameters.tcl
kratos.gid/apps/CDEM/xml/Main.spd
kratos.gid/apps/CDEM/xml/PartsCont.spd
kratos.gid/apps/CDEM/xml/SolutionStrategy.spd
kratos.gid/apps/DEM/xml/Conditions.xml
kratos.gid/apps/DEM/xml/Main.spd
kratos.gid/apps/DEM/xml/Parts.spd
kratos.gid/apps/DEM/xml/Processes.xml
kratos.gid/apps/DEM/xml/Results.spd
kratos.gid/apps/DEM/xml/SolutionStrategy.spd

fixed typos and added missing helps.

[DEM] tree changes

---

kratos.gid/apps/DEM/write/write_utils.tcl

First bugfix is for MeshCriteria in 2D. It was not meshing the lines acting as walls.
The second bugfix is needed again after it was tried by modifying the GUI core. In some cases it still fails.

[dem] Two bugfixes for meshing in 2D

---

kratos.gid/apps/Structural/examples/examples.tcl
kratos.gid/apps/Structural/examples/incompressible_cook_membrane.tcl
kratos.gid/apps/Structural/start.tcl
kratos.gid/apps/Structural/write/writeProjectParameters.tcl
kratos.gid/apps/Structural/xml/Elements.xml
kratos.gid/apps/Structural/xml/NodalConditions.xml
kratos.gid/apps/Structural/xml/XmlController.tcl

A 2D and 3D incompressible Cook membrane example is also added.
The Gauss pts. results issue is still pending.

[Structural] Mixed u-vol_ strain element addition

---

kratos.gid/scripts/Controllers/CommonProcs.tcl
kratos.gid/scripts/Controllers/TreeInjections.tcl
kratos.gid/scripts/Model/Element.tcl
kratos.gid/scripts/Model/Parameter.tcl

@maceligueta check it with your inlets... I think it's done

Change dependency system to TCL proc only

---

kratos.gid/apps/Buoyancy/xml/XmlController.tcl
kratos.gid/apps/ConvectionDiffusion/xml/Conditions.xml

Fortunately the number of deprecated conditions in the GUI was very limited
Related https://github.com/KratosMultiphysics/Kratos/pull/6475

Update the old names of deprecated conditions

---

kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl

[PfemFluid] Add new input to remesh block

---

kratos.gid/apps/CDEM/write/writeMDPA_Parts.tcl
kratos.gid/apps/CDEM/xml/ConstitutiveLawsC.xml

Bugfix. Some parameters were missing both in the tree and the mdpa

---

kratos.gid/apps/CDEM/xml/Conditions.xml
kratos.gid/apps/DEM/xml/Conditions.xml

This PR allows to use points when working with few particles.

[DEM] Adding element types missing in some of the BC

---

kratos.gid/apps/Dam/write/writeProjectParameters.tcl
kratos.gid/apps/Pfem/write/write.tcl
kratos.gid/apps/PfemFluid/write/ProjectParameters.json
kratos.gid/apps/Solid/write/write.tcl
kratos.gid/scripts/Writing/WriteProcess.tcl
kratos.gid/scripts/Writing/WriteProjectParameters.tcl

Implements KratosMultiphysics/Kratos/pull/6447
Implements #723

Replace frequency by output_interval

---

kratos.gid/apps/DEM/examples/CirclesDrop.tcl

temporal fix for example 2D. Assigned Rball instead of Granular until the mesher is fixed

bugfix DEM 2d Circle mesher

---

kratos.gid/scripts/Writing/WriteProjectParameters.tcl

Update VTK to KratosMultiphysics/Kratos/pull/7933

Replace vtk deprecated value to new output_path

---

kratos.gid/apps/PfemThermic/write/write.tcl
kratos.gid/apps/PfemThermic/xml/ConstitutiveLaws.xml

Adding temperature dependency tables for more material properties and a few adjustments.

Temperature dependency properties

---

kratos.gid/apps/DEMPFEM/python/MainKratos.py
kratos.gid/apps/Dam/python/dam_acoustic_script.py
kratos.gid/apps/Dam/python/dam_eigen_script.py
kratos.gid/apps/Dam/python/dam_main.py
kratos.gid/apps/Dam/python/dam_main_construction.py
kratos.gid/apps/Dam/python/dam_main_selfweight.py
kratos.gid/apps/FluidDEM/python/MainKratos.py
kratos.gid/apps/Pfem/python/RunPfem.py
kratos.gid/apps/Solid/python/RunSolid.py

Replace references to ExternalSolvers to LinearSolvers

Remove externalsolver references

---

kratos.gid/apps/DEM/xml/Conditions.xml

Kratos removed this type of condition because it was repeated

[dem] Fixing name of conditions printed (RigidEdge3DN to RigidFace3D2N)

---

kratos.gid/apps/StenosisWizard/wizard/Wizard_Steps.tcl
kratos.gid/apps/StenosisWizard/wizard/Wizard_default.wiz
kratos.gid/kratos.tcl
kratos.gid/scripts/Controllers/Drawer.tcl
kratos.gid/scripts/Utils.tcl

Add bending

---

kratos.gid/apps/Common/xml/GenericSubModelPart.spd

This could help
Implements #821

#821 proposal- add nodes info

---

kratos.gid/apps/ConvectionDiffusion/write/write.tcl

[FastPR][ConvDiff] Removing debugging leftover

---

kratos.gid/apps/ShallowWater/examples/HydraulicJump.tcl

minor update on the polynomial function

[Shallow] [Examples] More accurate topography

---

.gitignore
kratos.gid/apps/Buoyancy/app.json
kratos.gid/apps/CDEM/app.json
kratos.gid/apps/ConjugateHeatTransfer/app.json
kratos.gid/apps/ConvectionDiffusion/app.json
kratos.gid/apps/DEM/app.json
kratos.gid/apps/Dam/app.json
kratos.gid/apps/EmbeddedFluid/app.json
kratos.gid/apps/FSI/app.json
kratos.gid/apps/Fluid/app.json
kratos.gid/apps/FluidDEM/app.json
kratos.gid/apps/MPM/app.json
kratos.gid/apps/Structural/app.json
kratos.gid/apps/ThermicLauncher/app.json
kratos.gid/exec/launch.json
kratos.gid/scripts/Utils.tcl

Install python dependencies directly from pypi

Download dependencies

---

kratos.gid/apps/ShallowWater/xml/XmlController.tcl

Setting Z component to Null in BC

fix default value for velocity-Z

---

kratos.gid/apps/Dam/app.json
kratos.gid/apps/Dam/write/writeProjectParameters.tcl
kratos.gid/apps/Dam/xml/Conditions.xml

Customize the DamApplicaiton to use the common Kratos analysis.

[Dam] Customize the DamApplicaiton to use the common Kratos analysis

---

kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml

In this PR I'm adding several CL to the Structural ptype

[ConstitutiveLawsApp] Adding more CL to the interface

---

kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml

This PR follows the changes done in https://github.com/KratosMultiphysics/Kratos/pull/10191  in which I am adding a new plane stress cl and renaming the rest accordingly.

[ConstLawsApp] Renamig damage laws and adding plane stress

---

kratos.gid/apps/Common/xml/Processes.xml
kratos.gid/apps/FSI/xml/Conditions.xml

Keeping the base Process to be used as placeholder for the FSI interfaces.

[HotFix][FSI] Auxiliary placeholder Process

---

kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl
kratos.gid/apps/PfemFluid/xml/MeshBoxes.spd

Refining box can be repeated

---

kratos.gid/apps/Dam/xml/Elements.xml
kratos.gid/scripts/Writing/Writing.tcl

When meshing with prisms an error arose, this PR corrects it.

Meshing with prisms error

---

kratos.gid/apps/MPM/write/writeProjectParameters.tcl
kratos.gid/apps/MPM/xml/Results.spd

Include restart option in the MPM problemtype

MPM Restart Update

---

kratos.gid/apps/MPM/write/write.tcl

Grid mdpa should contain only grid nodes

---

kratos.gid/apps/MPM/write/write.tcl
kratos.gid/apps/MPM/xml/Elements.xml
kratos.gid/apps/MPM/xml/Procs.spd
kratos.gid/apps/MPM/xml/SolutionStrategy.spd
kratos.gid/apps/MPM/xml/XmlController.tcl

Fix #909 
@lauramoremar Can you check it?

Hotfix mpm stabilization

---

kratos.gid/apps/Dam/write/write.tcl
kratos.gid/apps/Dam/xml/Conditions.xml
kratos.gid/apps/Dam/xml/ConstitutiveLaws.xml
kratos.gid/apps/Dam/xml/Elements.xml
kratos.gid/apps/Dam/xml/Materials.xml
kratos.gid/apps/Dam/xml/Processes.xml

This PR adds new simplified joints for 2D and 3D problems. 
Also some clean up of unused elemnts has been carried out.

[Dam] Add new joints

---

kratos.gid/apps/Dam/xml/Processes.xml

Now, inside the Uplift conditions the user can specify the name of the joint part as their elements are needed in the computation. This solves issue #932

[Dam] Add joint elements to uplift condition

---

kratos.gid/apps/Common/xml/Elements.xml

Fixes #935 
Based on:
https://gidsimulation.atlassian.net/wiki/spaces/GRM/pages/2385547733/Element+type

Add quad elements

---

.github/workflows/tester.yml
kratos.gid/apps/Common/xml/GenericSubModelPart.spd
kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl
kratos.gid/apps/MdpaGenerator/app.json
kratos.gid/apps/MdpaGenerator/start.tcl
kratos.gid/apps/MdpaGenerator/write/write.tcl
kratos.gid/apps/MdpaGenerator/xml/Main.spd
kratos.gid/apps/MdpaGenerator/xml/Procs.spd
kratos.gid/apps/MdpaGenerator/xml/XmlController.tcl
kratos.gid/kratos.tcl
kratos.gid/scripts/Writing/WriteElements.tcl
kratos.gid/scripts/Writing/WriteGeometries.tcl
kratos.gid/scripts/Writing/WriteSubModelPart.tcl

Write geometries 

---

kratos.gid/apps/MPM/write/write.tcl

Fixes https://github.com/KratosMultiphysics/GiDInterface/pull/921#issuecomment-1770919689
Nodes that belong to groups assigned to boundary_conditions or conditions will be written in Grid.mdpa
@KratosMultiphysics/mpm

Hotfix mpm nodes

---

kratos.gid/apps/Fluid/write/write.tcl
kratos.gid/apps/Fluid/xml/Elements.xml
kratos.gid/apps/Fluid/xml/Strategies.xml

Adding div-stable P2-P1 element.

[Fluid] Div-stable element P2-P1

---

kratos.gid/apps/DEMLauncher/start.tcl
kratos.gid/apps/FluidLauncher/start.tcl
kratos.gid/apps/PfemLauncher/start.tcl
kratos.gid/apps/ThermicLauncher/start.tcl
kratos.gid/kratos.tcl
kratos.gid/scripts/Applications.tcl
kratos.gid/scripts/Controllers/ApplicationMarketWindow.tcl
tools/create-release.bat
tools/prepare-release-files.py

This scripts will help (me) to prepare the future releases.
Also making sure that references to unpublished apps do not appear in GUI

Prepare release script

---

kratos.gid/apps/Fluid/xml/Conditions.xml

This adds the possibility to set custom pressure conditions similarly to the custom velocity constraints. So far I only made it available for points in 2D and points and lines in 3D.
@jginternational we need to confirm that conditions are never written for this. In other words, we only need to write nodes in the submodelparts to which we assign this condition.

[Fluid] Pressure conditions

---

kratos.gid/apps/Dam/write/write.tcl
kratos.gid/apps/Dam/xml/ConstitutiveLaws.xml
kratos.gid/apps/Dam/xml/Materials.xml

After some tests, it has been decided to use the following interface:
- Elastic Cohesive
- Isotropic Damage Cohesive 
Other types of joints are not recommended for the nature of the problems addressed in the dam application.

[Dam] Add new joints to Dam app and remove old ones

---

kratos.gid/apps/Dam/write/write.tcl
kratos.gid/apps/Dam/xml/ConstitutiveLaws.xml

Correct joint constitutive law name in the Dam app and change some tags.

[Dam] Correct joint constitutive law name

---

kratos.gid/apps/MPM/app.json
kratos.gid/apps/MPM/examples/CantileverBeam.tcl
kratos.gid/apps/MPM/examples/FallingSandBall.tcl
kratos.gid/apps/MPM/examples/GranularFlow.tcl
kratos.gid/apps/MPM/examples/StaticCantileverBeam.tcl
kratos.gid/apps/MPM/write/writeProjectParameters.tcl
kratos.gid/apps/MPM/xml/ConstitutiveLaws.xml
kratos.gid/apps/MPM/xml/Elements.xml
kratos.gid/apps/MPM/xml/Main.spd
kratos.gid/apps/MPM/xml/Parts.spd
kratos.gid/apps/MPM/xml/Processes.xml
kratos.gid/apps/MPM/xml/XmlController.tcl

Related to https://github.com/KratosMultiphysics/Kratos/pull/12011

[MPM] Change application name

---

kratos.gid/apps/ConvectionDiffusion/app.json
kratos.gid/apps/ConvectionDiffusion/write/write.tcl
kratos.gid/apps/ConvectionDiffusion/write/writeProjectParameters.tcl
kratos.gid/scripts/Writing/WriteMaterials.tcl

It gets stacked
[convdiff_new.gid.zip](https://github.com/user-attachments/files/16286574/convdiff_new.gid.zip)

convection diffussion writes as geoms

---

kratos.gid/apps/EmbeddedFluid/app.json
kratos.gid/apps/EmbeddedFluid/write/writeProjectParameters.tcl
kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
kratos.gid/scripts/Writing/WriteProjectParameters.tcl
kratos.gid/scripts/spdAuxiliar.tcl

Embedded example works once migrated to geometries

Embedded migrate geoms

---

kratos.gid/apps/PotentialFluid/app.json
kratos.gid/apps/PotentialFluid/write/writeProjectParameters.tcl
kratos.gid/scripts/Writing/WriteProjectParameters.tcl

@rubenzorrilla 
A ver si le echas tambien un ojo en debug
[pot1.gid.zip](https://github.com/user-attachments/files/16282692/pot1.gid.zip)

Potential flow migration to geometries

---

kratos.gid/apps/Fluid/xml/Elements.xml
kratos.gid/apps/Fluid/xml/Strategies.xml

Adding the axisymmetric Navier-Stokes element to the GUI.

[FastPR][Fluid] Adding QS-VMS axisymmetric element
