KratosMultiphysics/GiDInterface

kratos.gid/apps/FSI/xml/Conditions.xml
Kratos deprecated conditions have been substituted by the current ones in the FSI interface conditions.
=> Kratos deprecated conditions

kratos.gid/apps/EmbeddedFluid/python/KratosFluid.py, kratos.gid/apps/Fluid/python/KratosFluid.py, kratos.gid/apps/Structural/python/KratosStructural.py
Python main scripts have been updated to make them as similar as possible between applications. A unique python script is used for both serial and parallel execution.
=> Updating Python scripts

kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml, kratos.gid/apps/Structural/xml/Elements.xml, kratos.gid/apps/Structural/xml/Strategies.xml, kratos.gid/scripts/Writing.tcl
This PR adds the new truss and shell elements to the structural mechanics application interface. The old beam element has been commented (once the local axes issue is completely addressed we can uncomment it to include the new corotational beam).
Recall that the truss element issue regarding the CROSS_AREA variable, which is required to be written as KratosMultiphysics.StructuralMechanicsApplication.CROSS_AREA, is still pending...
=> New structural application elements

kratos.gid/apps/Structural/write/writeProjectParameters.tcl
This PR removes the `restart_options` and the `constraints_data` from the Projectparameters
The restart options will be in the solver soon (I am working on this atm), the constraints data is not needed bcs this is done via processes
This is the first step of cleaning the Problemtype for release 5.3
=> StructralMechanics Removed unnecessary Parameters

kratos.gid/apps/Structural/xml/Elements.xml
This PR adds the prestress membrane elements to the interface
Also the shells can now be used both for tri and quad meshes, one does not have to select the geometry type (now it works the same as for the solids)
Step by step doing the stuff from the [TODO-List](https://github.com/KratosMultiphysics/GiDInterface/projects/9#column-1666919)
=> [StructuralMechanics] Adding new Elements

kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml, kratos.gid/apps/Structural/xml/Elements.xml, kratos.gid/apps/Structural/xml/Materials.xml
@KratosMultiphysics/structural-mechanics team, I've added the Bbar element together with the J2 constitutive model. However, I still have some doubts so I'm opening the PR to start the discussion.
- the Bbar elements can only work with the J2 cons. law or can we use other cons. laws?
- default values for the REFERENCE_HARDENING_MODULUS, REFERENCE_HARDENING_MODULUS, INFINITY_HARDENING_MODULUS and HARDENING_EXPONENT. Recall that in the interface we have as default materials steel and aluminium, so it would be nice if you can provide these magnitudes for these materials.
- are you interesting in any output variable different to the common ones?
=> Addition of Bbar element and J2 constitutive model to the interface

kratos.gid/kratos.tcl, kratos.gid/scripts/Controllers/MdpaImportMesh.tcl, kratos.gid/scripts/Menus.tcl
Utility to import an mdpa into the model.
Imports the nodes and the elements, according to Elements and Conditions, and generates groups according to SubModelParts
- It **does not interact with the Kratos tree** 
- It may **not keep the nodes and element id**, (if previous mesh existing in the model)
It can be found in the Kratos menu tab
Just mention @KratosMultiphysics/technical-committee so they can be informed of this new feature
=> Mdpa import mesh

kratos.gid/scripts/Writing.tcl
turns 
~~~
{
"properties" : [{
"model_part_name" : "Parts_Parts_Auto1",
"properties_id"   : 1,
"Material"        : {
"constitutive_law" : {
"name" : "KratosMultiphysics.StructuralMechanicsApplication.LinearElasticPlaneStress2DLaw"
},
"Variables"        : {
"THICKNESS"     : 1.0,
"DENSITY"       : 7850.0,
"YOUNG_MODULUS" : 206900000000.0,
"POISSON_RATIO" : 0.29
},
"Tables"           : {}
}
}]
}
~~~
into
~~~
{
"properties" : [{
"model_part_name" : "Parts_Parts_Auto1",
"properties_id"   : 1,
"Material"        : {
"constitutive_law" : {
"name" : "LinearElasticPlaneStress2DLaw"
},
"Variables"        : {
"THICKNESS"     : 1.0,
"DENSITY"       : 7850.0,
"YOUNG_MODULUS" : 206900000000.0,
"POISSON_RATIO" : 0.29
},
"Tables"           : {}
}
}]
}
~~~
@jginternational the …
=> removing "KratosMultiphysisc.AppName" from ConstLaw-Name

kratos.gid/apps/EmbeddedFluid/write/write.tcl, kratos.gid/apps/Fluid/write/write.tcl
@merceln @rubenzorrilla 
This fixes the write process
But it still not working
```
File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\python_solver.py", line 150, in _ImportModelPart
KratosMultiphysics.ModelPartIO(input_filename, import_flags).ReadModelPart(model_part)
RuntimeError: Error: Condition WallCondition2D3N is not registered in Kratos. Please check the spelling of the condition name and see if the application containing it is registered corectly. [Line 5173713 ]
```
=> Fix write conditions for embedded

kratos.gid/apps/Fluid/write/write.tcl, kratos.gid/scripts/Writing/WriteConditionsByUniqueId.tcl
Fixes /KratosMultiphysics/Kratos#3295
It wasn't ready for writing the grouped conditions by the new id system
@rubenzorrilla
=> Grouped conditions like slip must write submodelpart by unique id

kratos.gid/apps/Solid/symbols/symbols.tcl
In 2D direction has only two values and the expected direction vector requires three.
In the laptop with the 2K screen no symbol is shown.... Do you think there is something wrong related with the resolution scale @escolano?
There is also another thing. When a direction is zero, because it has not been assigned correctly, it fails to do the norm and a big error/warning message appears. It is possible to check it before and add a small warning message saying that direction is wrong and has to be corrected?
Thank you in advance!
=> [Solid] fix symbol draw in 2D 

kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl, kratos.gid/apps/FSI/xml/GetFromXML.tcl
Fix in the ALE mesh boundary conditions in the Mok benchmark example and addition of the mesh motion variables to the fluid nodal output variables.
=> [FSI] Mesh motion output and mok fix

kratos.gid/apps/Buoyancy/examples/HeatedSquare.tcl, kratos.gid/apps/Buoyancy/xml/ConstitutiveLaws.xml
@jginternational  by updating this I did realize that the Buoyancy and CHT interfaces are always writing the material properties of the Air instead of the user-defined ones. 
With this settings, one should obtain the expected results as long as the writing is fixed.
=> [Buoyancy] Example case as reference test in literature

kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml
@KratosMultiphysics/structural-mechanics guys, while checking the Turek benchmark in the FSI application I did realize that the CLAWS names in the StructuralMechanicsApplication GUI were different to the Kratos Python exported ones. 
Would you mind checking that everything is fine?
=> [Structural] Kratos name correction

kratos.gid/apps/PotentialFluid/examples/NACA0012.tcl, kratos.gid/apps/PotentialFluid/python/KratosPotentialFluid.py, kratos.gid/apps/PotentialFluid/xml/Processes.xml
This is a small pull request to remove the setting of the potential in the inlet and the wake direction.
The potential at the inlet does not affect the results so it will be automatically set inside Kratos and the wake direction is always the free stream direction.
I updated the example as @rubenzorrilla showed me.
=> Removing inlet and wake direction (they are internally defined in Kratos)

kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
If we use a not-moving wall the program did not work because fixed_mesh_option, rigid_body_motion and free_body_motion were not defined.
Also change deprecated WALL_FRICTION by FRICTION
=> [DEM] Correct walls attributes

kratos.gid/apps/DEM/write/write.tcl, kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl, kratos.gid/apps/DEM/write/write_utils.tcl
In DEM Parts created over points, lines or surfaces, using the custom mesher, we must tell the writing procedures that the elements will be volumes (spheres) instead of points, lines...
In addition, I've fixed the mesher algorithm that tried to delete elements by element type even if the group didn't contain that element type.
@KratosMultiphysics/dem
=> change ov in groups that did not use the GiD mesher

kratos.gid/apps/DEM/xml/Processes.xml, kratos.gid/scripts/Controllers/TreeInjections.tcl
Hi @KratosMultiphysics/dem people,
GiD is deploying it's 14.1.4d version soon. In this version, we include a new parameter to hide entries in the conditions window, but show it the tree.
So, with this PR, the condition DEM-FEM Wall will change from this:
to this:
But in the tree:
So you can check this development and implement it in the rest of laaaarge processes DEM uses.
=> Reduce large number of parameters in conditions window

kratos.gid/apps/FSI/examples/HighRiseBuilding.tcl, kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl, kratos.gid/apps/FSI/examples/TurekBenchmark.tcl, kratos.gid/apps/FSI/xml/Main.spd, kratos.gid/apps/FSI/xml/Procs.spd, kratos.gid/apps/Structural/examples/HighRiseBuilding.tcl, kratos.gid/apps/Structural/examples/TrussCantilever.tcl, kratos.gid/apps/Structural/write/write.tcl, kratos.gid/apps/Structural/write/writeProjectParameters.tcl, kratos.gid/apps/Structural/xml/Elements.xml, kratos.gid/apps/Structural/xml/GetFromXML.tcl, kratos.gid/apps/Structural/xml/NodalConditions.xml, kratos.gid/apps/Structural/xml/Parts.spd, kratos.gid/apps/Structural/xml/Procs.spd, kratos.gid/scripts/Controllers/TreeInjections.tcl, kratos.gid/scripts/Writing/WriteElements.tcl, kratos.gid/scripts/Writing/WriteMaterials.tcl, kratos.gid/scripts/Writing/Writing.tcl
I've been working in the assignation of parts of the Structural application
Until now, it was a little bit confusing, as it's explained in the following example. The user didn't know which geometry type was available for each element, and the different elements were mixed in the 'Element' dropdown.
Thes PR improves the UX by grouping the elements in families, so the shells will be together, the beams, the membranes...
All you can see, all the elements are in the same dropdown, and the user must select the geometry type (line, surface, volume) to set the assignation.
Since each element type in this app can only be assigned to a single geometry type, this is a non-sense. Membranes are only available for surfaces, cables to lines....
Now, the user 'double-clicks' on Parts > Shells (the …
=> Parts by 'element family'

kratos.gid/apps/Structural/xml/Strategies.xml
implements #632 
It appears in the tree in the strategy parameters:
And in the json:
```
"solver_settings"  : {
"solver_type"                     : "Dynamic",
"model_part_name"                 : "Structure",
"domain_size"                     : 2,
"echo_level"                      : 0,
"analysis_type"                   : "non_linear",
"time_integration_method"         : "implicit",
"scheme_type"                     : "newmark",
"model_import_settings"           : {
"input_type"     : "mdpa",
"input_filename" : "raileig_example"
},
"material_import_settings"        : {
"materials_filename" : "StructuralMaterials.json"
},
"time_stepping"                   : {
"time_step" : 0.05
},
"raileigh_alpha"                  : 0.01,
"raileigh_beta"                   : 0.02,
"line_search" …
```
=> Add raileigh parameters to implicit

kratos.gid/apps/DEM/write/write_utils.tcl, kratos.gid/kratos.tcl
The problem was the following:
1- Group created and assigned to condition DEM-FEM-Wall
2- Mesh (MeshCriteria Mesh is applied to the surfaces in the group)
3- You unassign some surfaces from that group
4- Mesh -> BUG: some surfaces are being meshed that should not be. Nobody was resetting the MeshCriteria Mesh.
I don't see how I can fix this bug in a different way. I know that this may interfere with other applications coupled with DEM.
=> Meshcriteria is resetted on all surfaces of the model

kratos.gid/apps/DEM/start.tcl, kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl, kratos.gid/apps/DEM/xml/Conditions.xml, kratos.gid/apps/DEM/xml/Processes.xml, kratos.gid/apps/DEM/xml/XmlController.tcl, kratos.gid/scripts/Writing/WriteElements.tcl
This implements #677
It fails because, as it prints spheres in the DEM.mdpa, those spheres need properties, and fail if no const law is defined inside it....
Please test it and decide about it @KratosMultiphysics/dem
=> Hotfix dem customsmp

kratos.gid/apps/Common/xml/Solvers.xml, kratos.gid/apps/Dam/xml/Solvers.xml, kratos.gid/apps/MPM/xml/XmlController.tcl, kratos.gid/apps/Pfem/write/ProjectParameters.json, kratos.gid/apps/Pfem/xml/Solvers.xml, kratos.gid/apps/PfemFluid/write/ProjectParameters.json, kratos.gid/apps/PfemFluid/xml/Solvers.xml
Required changes according to https://github.com/KratosMultiphysics/Kratos/pull/6741.
@jginternational note that the `ExternalSolversApplication` is being deprecated in favour of the `EigenSolversApplication`. We should start packaging the second one instead of the first one.
Another question I have is why the PFEM applications are not using the common `solvers.xml`. As far as I see they have exactly the same solvers.
=> [All] Linear solvers clean up

kratos.gid/apps/Fluid/write/writeProjectParameters.tcl, kratos.gid/apps/Fluid/xml/AnalysisType.spd, kratos.gid/apps/Fluid/xml/Strategies.xml
After [#6879](https://github.com/KratosMultiphysics/Kratos/pull/6879) it would be possible to use the `BDF2` scheme with slip BCs. Hence, we can expose it in the CFD GUI when selecting monolithic strategies.
=> [Fluid] Add monolithic time scheme selection

kratos.gid/apps/PotentialFluid/write/write.tcl
Closes #751 
Predefined example was failing because the sub_model_part_names in the processes and materials did not have the "parent_model_part".
=> [PotentialFlow] [Fix] Setting model_part_name attribute 

kratos.gid/scripts/Controllers/TreeInjections.tcl
The element results container was hidden due to a change in the way the Structural app shows it's elements.
Now this is what user sees when selecting a Solid part, with Small displacement element
=> Hotfix -> Gauss point result hidden in some apps like Structural

kratos.gid/apps/Buoyancy/xml/ConstitutiveLaws.xml, kratos.gid/apps/Buoyancy/xml/Materials.xml, kratos.gid/apps/Fluid/write/writeProjectParameters.tcl, kratos.gid/apps/Fluid/xml/ConstitutiveLaws.xml, kratos.gid/apps/Fluid/xml/Elements.xml, kratos.gid/apps/Fluid/xml/Materials.xml, kratos.gid/apps/Fluid/xml/Strategies.xml, kratos.gid/apps/FluidDEM/xml/Elements.xml
This PR fixes some inconsistencies in the `formulation` dictionary. Furthermore it adds the new `WeaklyCompressibleNavierStokes` element to the GUI.
`Buoyancy` and `FluidDEM` applications have been updated accordingly so everything should work fine.
(we need to first merge [7997](https://github.com/KratosMultiphysics/Kratos/pull/7997) in the Kratos main repo).
=> [Fluid] Fluid fixes and weakly compressible element addition

kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl, kratos.gid/apps/FSI/examples/TurekBenchmark.tcl, kratos.gid/apps/FSI/write/writeProjectParameters.tcl
=> Hotfix fsi submodelparts

kratos.gid/scripts/Writing/WriteNodes.tcl
Fixes #811 
It is unefficient now but this will apply the unit factor to the printed node coordinates.
In future GiD versions we will be able to apply this factor via c++ in `GiD_WriteCalculationFile nodes` like we do in `GiD_WriteCalculationFile coordinates` 
Check -> https://gidsimulation.atlassian.net/wiki/spaces/GCM/pages/2410447127/WriteCalculationFile
=> inefficient way but must wait to future versions of gid

kratos.gid/kratos.tcl, kratos.gid/scripts/Controllers/Preferences.xml, kratos.gid/scripts/Controllers/PreferencesWindow.tcl, kratos.gid/scripts/Menus.tcl, kratos.gid/scripts/Utils.tcl, kratos.gid/scripts/Writing/WriteProjectParameters.tcl, kratos.gid/scripts/Writing/Writing.tcl
This PR just generates the files to make the life a little bit easier to a VSCode debugger.
- Open the Kratos preferences -> from the main window, or in the top menú Kratos > Preferences
- Select Developer mode
- Pick the Kratos debug compiled folder -> %your_kratos_repository_folder%/Kratos/bin/Debug
- This preferences are stored for future sessions.
- Generate your case, mesh it and write the input files (Click on calculate or Kratos > Write calculation files)
- Open your case folder in Visual Studio Code
- Place a breakpoint somewhere in the MainKratos.py file in the case
- Click on the debug tab, and run the python main configuration.
- When it hits the breakpoint, you can also attach the c++ debugger (see how at the end of the video) …
=> Debug a case execution using VSCode and GiD Interface

kratos.gid/apps/Common/xml/Processes.xml
The common process `AssignVectorVariableToConditionProcess` had a Kratos process name of:
```
python_module="assign_vector_variable_to_condition_process"
```
which is wrong. In kratos, the word `condition` in the process name is plural `conditions`. See [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/assign_vector_variable_to_conditions_process.py).
This typo went unnoticed because it's not in use by any app at the moment.
=> Fixed wrong process name AssignVectorVariableToConditionProcess

kratos.gid/apps/ConvectionDiffusion/app.json
Setting the application settings to output the main model part instead of the computing one, which is no longer used.
=> [FastPR][ConvDiff] Update output to MainModelPart

kratos.gid/scripts/Controllers/TreeInjections.tcl
This PR enables the new GiD feature (15.1.4d) to configure conditions:
When double click on a condition, dont allow the creation of new groups. Execute a tcl proc to return a group list, so the user can select from that list. Useful in the new @KratosMultiphysics/dem  app
Copy and pase this sections to see the changes (I don't add them to the PR because we dont want them to exist yet)
- file `kratos.gid/apps/DEM/xml/Conditions.xml` line 21: 
```xml
<ConditionItem n="DEM-FEM-Wall2D" pn="Rigid Walls" Interval="False" 
ImplementedInApplication="DEMApplication" MinimumKratosVersion="9000" 
ProductionReady="ProductionReady" WorkingSpaceDimension="2D" 
LocalSpaceDimension="1" ElementType="Line" ProcessName="DEM-FEM-Wall-Process" 
help="Assign kinematic conditions for each group containing …
```
=> Condition only existing groups

kratos.gid/apps/Common/xml/Results.spd, kratos.gid/scripts/Writing/WriteProjectParameters.tcl
This field allows apps to store the postprocess files into a folder easily
VTK output stores the files in vtk_output, so they don't disturb the model files
This PR adds a field in the GUI
So all the postprocess files will be created inside a folder (except the .post.lst one, that must be on the root)
The effect on the ProjectParameters.json section is that the output_name has the folder prepended:
```json
"gid_output" : [{
"python_module" : "gid_output_process",
"kratos_module" : "KratosMultiphysics",
"process_name"  : "GiDOutputProcess",
"help"          : "This process writes postprocessing files for GiD",
"Parameters"    : {
"model_part_name"        : "FluidModelPart.fluid_computational_model_part",
*"output_name"            : "gid_output/folder",*
"postprocess_parameters" : { …
```
=> Gid output folder

kratos.gid/apps/PfemThermic/write/writeProjectParameters.tcl
Removed an unused field from ProjectParameters.json file.
Now the thermal PFEM examples are running again.
=> Fix in ProjectParameters Writting

kratos.gid/scripts/Model/Condition.tcl, kratos.gid/scripts/Model/Element.tcl, kratos.gid/scripts/Writing/WriteConditions.tcl, kratos.gid/scripts/Writing/Writing.tcl
Fixes #886 
Old code was working for linear topologies on conditions because of a trick (string pattern macht instead of string compare)
This was not implemented in elements so it was failing there.
Now all topology searches are by geometry names and number of nodes. p.e: Line 2 -> LineCondition2D2N
=> Hotfix linear topologies

kratos.gid/apps/Common/xml/Processes.xml, kratos.gid/apps/FSI/xml/Conditions.xml
Following [this](https://github.com/KratosMultiphysics/Kratos/pull/8039) in the main repository, this PR removes the deprecated `PythonProcess`.
=> [All] Remove deprecated PythonProcess

kratos.gid/apps/MPM/write/write.tcl, kratos.gid/apps/MPM/xml/Elements.xml
**📝 Description**
Information about the Background grid has been deleted in the ParticleMaterials.json:
=> [MPM] Information about background_grid deleted in ParticleMaterials.json

kratos.gid/apps/Fluid/xml/Processes.xml
Minor fix in the `wall_model_name` field in the `ApplyWallLawProcess`.
closes #923.
=> [FastPR][Fluid] wall_model_name hotfix

kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
After #924 the file `ProjectParameters.json` is not written when using the wall law condition. 
Fixing this issue.
=> [FastPR][Fluid] wall_model_name hotfix (part 2)

kratos.gid/apps/FreeSurface/xml/Main.spd, kratos.gid/apps/FreeSurface/xml/Parts.spd, kratos.gid/apps/FreeSurface/xml/XmlController.tcl
Some options available in the problemtype were not really used in by Kratos Free Surface Application
=> [FreeSurface] Remove unused options in the Free Surface Application

kratos.gid/scripts/Controllers/MdpaImportMesh.tcl
Import MDPA feature did not import quadratic lines properly
ALSO import MDPA with geometries
Only quadratic lines and linear triangles were having problems, since they are both 2D and 3 nodes.
The rest of entities with the same nodes can be determined by the dimension:
4 noded linear quadrilateral and tetrahedra (2D <-> 3D)
6 noded quadratic triangles and linear prism (2D <-> 3D)
8 noded quadratic quadrilateral and linear hexaedra (2D <-> 3D)
The rest do not share number of connectivities
https://gidsimulation.atlassian.net/wiki/spaces/GRM/pages/2385547733/Element+type
=> MDPA Import Geometries & quadratic mesh

kratos.gid/apps/Structural/write/writeProjectParameters.tcl
Fixes #946 
Adds
```
builder_and_solver_settings" : {
"use_block_builder" : false
}
```
to the Project parameters > solver settings if eigen analysis is selected
No chance for the user to change it in the GUI
=> Add use_block_builder to false in eigen analysis

kratos.gid/apps/GeoMechanics/app.json, kratos.gid/scripts/Applications.tcl
In app.json, the application can now define the default mesh type for it's models.
By default, it's not modified.
If the app sets it to 'quadratic' it will be set in the Start event, so the user can change it later.
If the app sets it to anything else, it will be set as linear
Just for testing, geomechanics sets it to quadratic
=> App mesh type

kratos.gid/apps/MPM/examples/CantileverBeam.tcl, kratos.gid/apps/MPM/examples/GranularFlow.tcl, kratos.gid/apps/MPM/examples/StaticCantileverBeam.tcl
Fixed the FixedDisplacement group in MPM examples.
This boundary condition didn't appear as a "group" in the GiD pannel interface.
=> FixedDisplacement group fixed in MPM examples

kratos.gid/apps/MPM/write/writeProjectParameters.tcl
Change names of deprecated vtk parameters (parameters have changed due to https://github.com/KratosMultiphysics/Kratos/pull/11140)
- `folder_name` becomes `output_path`
- `gauss_point_results` becomes `gauss_point_variables_in_elements`
=> [MPM] Change deprecated VTK parameters names

kratos.gid/apps/Stent/start.tcl, kratos.gid/apps/Structural/start.tcl, kratos.gid/apps/Structural/write/write.tcl, kratos.gid/kratos.cnd
This PR will remove an annoying warning when using lines in Structural mechanics app
The feature may affect  Structural > Beams > Hinges.
Until this PR we were getting the mdpa data:
```
Begin ElementalData CONDENSED_DOF_LIST // Group: Hinge Auto1
25 [3] (0,1,2)
38 [3] (3,4,5)
End ElementalData
```
Being 25 and 38 the starting node and final node of the line with boundary condition > Hinge
The way we used to pick this numbers was:
- Get the list of nodes of the line
- Sort them numerically (not following the line normal, just sort the ids)
- Get min and max
This works fine since GiD meshes this way **but**:
- Mesh could be renumbered
- This does not preserve the direction of the geometrical line.
- To get the relation between the geometrical line and the nodes, we were using an old gid …
=> New line geom mesh relation

kratos.gid/apps/Dam/examples/ThermoMechaDam2D.tcl, kratos.gid/apps/Dam/write/write.tcl, kratos.gid/apps/Dam/write/writeProjectParameters.tcl, kratos.gid/apps/Dam/xml/Processes.xml
- Add INITIAL_JOINT_WIDTH as default to joint properties.
- Change some variable names and improve some comments.
- Fix TableId initialization as groupid variable was not written properly, now: set groupid [write::GetWriteGroupName $groupid]
This PR fixes issue #981.
=> [Dam] Add initial joint width to joints and fix problem with tables

kratos.gid/apps/Structural/app.json, kratos.gid/apps/Structural/write/write.tcl, kratos.gid/apps/Structural/write/writeProjectParameters.tcl, kratos.gid/scripts/Writing/WriteMaterials.tcl
Another one I can not run @rubenzorrilla 
[structure_as_geometry.gid.zip](https://github.com/user-attachments/files/16284900/structure_as_geometry.gid.zip)
=> Migrate structural

kratos.gid/apps/FreeSurface/app.json, kratos.gid/apps/FreeSurface/write/writeProjectParameters.tcl, kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Free surface fails running because of this:
In the first picture we can see the the group Fluid:
In the second picture we can see the group Surface bottom:
They do share elements
In the MDPA, both groups are written as `Begin Geometries Triangle2D3`
So there are elements declared 2 times, with the same id and the same connectivities. This should not be a problem, but it is.
You can see the log:
```
File "C:\Users\garat\Desktop\Deploy_Kratos\Deploy_Kratos\KratosMultiphysics\analysis_stage.py", line 80, in Initialize
self._ModelersSetupModelPart()
File "C:\Users\garat\Desktop\Deploy_Kratos\Deploy_Kratos\KratosMultiphysics\analysis_stage.py", line 285, in _ModelersSetupModelPart
modeler.SetupModelPart()
File "C:\Users\garat\Desktop\Deploy_Kratos\Deploy_Kratos\KratosMultiphysics\modelers\impor …
```
=> Free surface writes geometries
